PRODUCT_CATALOG = {
    "garri": {
        "aliases": ["garri", "gari", "white garri", "yellow garri", "ijebu garri"],
        "category": "staple",
        "default_unit": "kg",
        "common_units": ["kg", "paint bucket", "bag", "cup"],
    },
    "rice": {
        "aliases": ["rice", "local rice", "foreign rice", "ofada rice"],
        "category": "grain",
        "default_unit": "kg",
        "common_units": ["kg", "50kg bag", "25kg bag", "10kg bag", "cup", "paint bucket"],
    },
    "beans": {
        "aliases": ["beans", "ewa", "oloyin", "white beans", "brown beans"],
        "category": "grain",
        "default_unit": "kg",
        "common_units": ["kg", "paint bucket", "cup", "bag"],
    },
    "yam": {
        "aliases": ["yam", "tuber of yam", "isu"],
        "category": "staple",
        "default_unit": "tuber",
        "common_units": ["tuber", "piece", "kg"],
    },
    "tomato": {
        "aliases": ["tomato", "tomatoes", "fresh tomato", "fresh tomatoes"],
        "category": "vegetable",
        "default_unit": "kg",
        "common_units": ["kg", "basket", "paint bucket"],
    },
    "pepper": {
        "aliases": ["pepper", "fresh pepper", "atarodo", "rodo", "scotch bonnet"],
        "category": "vegetable",
        "default_unit": "kg",
        "common_units": ["kg", "basket", "paint bucket"],
    },
    "onion": {
        "aliases": ["onion", "onions", "albasa"],
        "category": "vegetable",
        "default_unit": "kg",
        "common_units": ["kg", "bag", "basket", "paint bucket"],
    },
    "okra": {
        "aliases": ["okra", "okro", "ila"],
        "category": "vegetable",
        "default_unit": "kg",
        "common_units": ["kg", "paint bucket", "basket"],
    },
    "efo": {
        "aliases": ["efo", "green leaf", "vegetable leaf", "spinach"],
        "category": "leafy_vegetable",
        "default_unit": "bunch",
        "common_units": ["bunch", "bundle", "basket"],
    },
    "ugu": {
        "aliases": ["ugu", "ugwu", "pumpkin leaf", "fluted pumpkin"],
        "category": "leafy_vegetable",
        "default_unit": "bunch",
        "common_units": ["bunch", "bundle", "basket"],
    },
    "bitter leaf": {
        "aliases": ["bitter leaf", "ewuro", "onugbu"],
        "category": "leafy_vegetable",
        "default_unit": "bunch",
        "common_units": ["bunch", "bundle", "basket"],
    },
    "waterleaf": {
        "aliases": ["waterleaf", "gbure"],
        "category": "leafy_vegetable",
        "default_unit": "bunch",
        "common_units": ["bunch", "bundle"],
    },
    "egusi": {
        "aliases": ["egusi", "melon seed", "ground egusi"],
        "category": "seed",
        "default_unit": "kg",
        "common_units": ["kg", "cup", "paint bucket", "bag"],
    },
    "ogbono": {
        "aliases": ["ogbono", "ogbolo", "wild mango seed"],
        "category": "seed",
        "default_unit": "kg",
        "common_units": ["kg", "cup"],
    },
    "crayfish": {
        "aliases": ["crayfish", "dried crayfish"],
        "category": "protein",
        "default_unit": "kg",
        "common_units": ["kg", "cup", "paint bucket"],
    },
    "palm oil": {
        "aliases": ["palm oil", "red oil", "epo pupa"],
        "category": "oil",
        "default_unit": "litre",
        "common_units": ["litre", "bottle", "gallon", "25l keg"],
    },
    "egg": {
        "aliases": ["egg", "eggs", "crate of egg", "crate of eggs"],
        "category": "protein",
        "default_unit": "crate",
        "common_units": ["piece", "crate"],
    },
    "chicken": {
        "aliases": ["chicken", "fowl", "broiler"],
        "category": "protein",
        "default_unit": "kg",
        "common_units": ["kg", "whole chicken", "piece"],
    },
    "beef": {
        "aliases": ["beef", "meat", "cow meat"],
        "category": "protein",
        "default_unit": "kg",
        "common_units": ["kg"],
    },
    "tatashe": {
        "aliases": ["tatashe", "red bell pepper", "bell pepper"],
        "category": "vegetable",
        "default_unit": "kg",
        "common_units": ["kg", "basket", "paint bucket"],
    },
    "shombo": {
        "aliases": ["shombo", "shonbo", "long pepper", "cayenne pepper"],
        "category": "vegetable",
        "default_unit": "kg",
        "common_units": ["kg", "basket", "paint bucket"],
    },
    "ginger": {
        "aliases": ["ginger", "fresh ginger"],
        "category": "condiment",
        "default_unit": "kg",
        "common_units": ["kg", "bag"],
    },
}